# Use the official Python image from the Docker Hub
FROM python:3.12-slim

# Set environment variables and install Poetry in a single step
ENV POETRY_VERSION=1.8.3 \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    PATH="/root/.local/bin:$PATH"

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl && \
    curl -sSL https://install.python-poetry.org | python3 - && \
    apt-get purge -y --auto-remove curl && \
    rm -rf /var/lib/apt/lists/*

# Change directory to one up from the Dockerfile
WORKDIR /app

# Copy the current directory contents into the container
COPY . .

# Install dependencies with the smallest size for production
RUN poetry install --no-dev --no-root

# Run the application
CMD ["poetry", "run", "python", "/app/app/main.py"]
