# Use the official Python image from the Docker Hub
FROM python:3.12-slim

# Set environment variables
ENV POETRY_VERSION=1.8.3 \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    PATH="/root/.local/bin:$PATH"

# Install Poetry
RUN apt-get update && \
    apt-get install -y curl && \
    curl -sSL https://install.python-poetry.org | python3 - && \
    apt-get clean

# Change directory to one up from the Dockerfile
WORKDIR /app

# Copy the current directory contents into the container
COPY . .

# Install dependencies
RUN poetry install

# Run the application
CMD ["poetry", "run", "python", "/app/app/main.py"]
